# Generated by Django 4.1.5 on 2023-01-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('requirments', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('deadline', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('userName', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('password1', models.CharField(max_length=255)),
                ('password2', models.CharField(max_length=255)),
            ],
        ),
    ]
